name: Test/Deploy docker-react

on:
    push: 
        branches: 
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: docker login -u hemanthkumarrajoli -p Test@1234
            - run: docker build -t hemanthkumarrajoli/react-test -f Dockerfile.dev .
            - run: docker run -e CI=true hemanthkumarrajoli/react-test npm run test